---
title: "José Miguel Avendaño C.V."
subtitle: "A Visual Datascientist"
author: Jose M Avendano
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: false
  cache_data:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1RVmybm100fCVyvKZyEX1MJsKUz1Qppou2_y_ydiiuCg/edit#gid=1381329386",  
  pdf_mode = params$pdf_mode,
  cache_data = params$cache_data
)
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("Ver este currículo en línea en _https://github.com/javendaXgh/cv/raw/master/cv_JMAI.pdf_")
} else {
  cat("[<i class='fas fa-download'></i> Descargar un PDF de este currículo](https://github.com/javendaXgh/cv/raw/master/javenda_cv.pdf)")
}
```

Contacto {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Lenguajes de Programación {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------



El código fuente está disponible en [on github.com/nstrayer/cv](https://github.com/nstrayer/cv).

Última actualización: `r Sys.Date()`.



Main
================================================================================

José Miguel Avendaño I. {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Educación {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
```{r}
CV %<>% print_section('educación')
```

<!-- These breaks just force a new page so section doesnt get cut off -->

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



Cursos a distancia {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('academic_articles_aside')
```
::: 

```{r}
CV %<>% print_section('academic_articles')
```


Experiencia en Investigación {data-icon=laptop}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
::: 

```{r}
CV %<>% print_section('research_positions')
```




Experiencia Sector Gobierno  {data-icon=suitcase}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('industry_positions')
```

::: aside
```{r}
CV %<>% print_text_block('industy_experience_aside')
```


<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

:::
Experiencia de enseñanza {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```







